### PR TITLE
Fixes flockdrones not being able to put items into lockers

### LINKED ISSUE #105: Flockdrones can't put items in storage containers
### Labels

[BUG]

### Description

Flockdrones can't put items in storage containers like crates and lockers.

### Steps to reproduce

1. Be a Flockdrone
2. Pick an item up
3. Left click a storage container

### Expected Behavior

For the item to be put into the container rather than dropped at the Flockdrone's location.

### Additional Information & Screenshots

_No response_

### PR DESCRIPTION
**Pull request by TobleroneSwordfish**
[BUG]
## About the PR 
Fixes #105, technically this is an upstream bug but it's so minor we may as well just lump it in with flock? Can move this to upstream if needed.

## Why's this needed? 
bug

### CODE REVIEW

**Comment by FlameArrow57** [comment]
Nice! Yeah, might be good to upstream pr, as it might mean that ghost critters can now put objects in containers?

**Comment by TobleroneSwordfish** [comment]
alright I PRed it upstream: https://github.com/goonstation/goonstation/pull/8480
feel free to close this if/when that gets merged

**Comment by FlameArrow57** [comment]
Cool, there was also some code in the flock closet file that was used to fix this I think for Flock closets, maybe could be removed instead in this PR or done later in the cleanup PR.

**Comment by TobleroneSwordfish** [comment]
fixed upstrem

**Pull request closed without merging**
